---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600
- name: Install dirmngr in order to be able to install the apt signing key
  apt:
    pkg:
      - dirmngr
- name: Add PPA Key for deadsnakes
  apt_key:
    id: F23C5A6CF475977595C89F51BA6932366A755776
    keyserver: keyserver.ubuntu.com
- name: Extract distribution base name (works on linux mint as well)
  command: grep -oP '{{ "VERSION" if ansible_distribution == "Debian" else "UBUNTU" }}_CODENAME=\K.*' /etc/os-release
  register: distro
  changed_when: False
- name: Add deadsnakes PPA (deb)
  apt_repository:
    repo: deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu {{ distro.stdout }} main
- name: Add deadsnakes PPA (deb-src)
  apt_repository:
    repo: deb-src http://ppa.launchpad.net/deadsnakes/ppa/ubuntu {{ distro.stdout }} main
- name: Install Python and associated packages
  apt:
    pkg:
      - python2.7
      - python2.7-dev
      - python3
      - python3-dev
      - python3-venv
      - python3.6
      - python3.6-dev
      - python3.6-venv
      - python-lxml
      - python3-lxml
- name: Install pipenv
  block:
  - name: Install pipenv via package manager
    apt:
      pkg: pipenv
  rescue:
    - name: Install pipenv without package manager
      include_role:
        name: baztian.pip_venv
      vars:
          pkg: pipenv
          version: 2018.11.26
- name: install tox
  apt:
    pkg: tox
- name: Gather installed packages
  package_facts:
- name: Install tox via pip_venv
  include_role:
    name: baztian.pip_venv
  vars:
      pkg: tox
      version: "{{ tox_version }}"
  when: "ansible_facts.packages['tox'][0]['version']|default(0)
    is version (tox_version, '<')"
